title: How to add datasets to renku
description: A how-to!
template:
  repo: how-to-add-datasets-to-renku-template
  name: how-to-add-datasets-to-renku
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
      - type: createFile
        filename: Dockerfile
  - title: New step
    actions:
      - type: createIssue
        title: A new issue
        body: a-response-file.md
